apiVersion: apps/v1
kind: Deployment
metadata:
  name: impostor
  labels:
    app: impostor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: impostor
  template:
    metadata:
      labels:
        app: impostor
    spec:
      containers:
        - name: impostor
          image: ghcr.io/npastorale/impostor:latest@sha256:8ed0549558aab76a66a9b0c9a3af6fba04ae365a3a257eeaaa9d5f9b5b9da7c8
          resources:
            requests:
              memory: "56Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
