apiVersion: apps/v1
kind: Deployment
metadata:
  name: impostor
  labels:
    app: impostor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: impostor
  template:
    metadata:
      labels:
        app: impostor
    spec:
      containers:
        - name: impostor
          image: ghcr.io/npastorale/impostor:latest@sha256:999b7fbbd60fcf3d4e7a5b2b4f18f188f55043950898698022a30c451b5a0b12
          resources:
            requests:
              memory: "56Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
