apiVersion: apps/v1
kind: Deployment
metadata:
  name: impostor
  labels:
    app: impostor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: impostor
  template:
    metadata:
      labels:
        app: impostor
    spec:
      containers:
        - name: impostor
          image: ghcr.io/npastorale/impostor:latest@sha256:e7288e3acac2fee92d9c5668ba850100754ddf39f5a4e7ba1c59f1890c073210
          resources:
            requests:
              memory: "56Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
