apiVersion: apps/v1
kind: Deployment
metadata:
  name: impostor
  labels:
    app: impostor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: impostor
  template:
    metadata:
      labels:
        app: impostor
    spec:
      containers:
        - name: impostor
          image: ghcr.io/npastorale/impostor:latest@sha256:110d8a866e03b71487e83e3750d24a1f934535d522d5b3450a5b630605e1850d
          resources:
            requests:
              memory: "56Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
