apiVersion: apps/v1
kind: Deployment
metadata:
  name: slides
  labels:
    app: slides
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slides
  template:
    metadata:
      labels:
        app: slides
    spec:
      containers:
        - name: slides
          image: npastorale/slides
          resources:
            requests:
              memory: "56Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
