resources:
  - ../../base

patches:
  - target:
      kind: PersistentVolumeClaim
      name: config
    path: PersistentVolumeClaim.yaml
  - target:
      kind: Ingress
      name: http-server
    path: Ingress.yaml
