resources:
  - Deployment.yaml
  - HorizontalPodAutoscaler.yaml
  - Ingress.yaml
  - PersistentVolumeClaim.yaml
  - Service.yaml
configMapGenerator:
  - name: default-conf
    files:
      - default.conf
  - name: nginx-conf
    files:
      - nginx.conf
